# autograd

In [ ]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights = ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [3]:
prediction = model(data)

In [4]:
loss = (prediction - labels).sum()
loss.backward()

In [5]:
optim = torch.optim.SGD(model.parameters(), lr = 1e-2, momentum = 0.9)

In [6]:
optim.step()

In [ ]:
epochs = 1000
for epoch in range(epochs):
    # 前向传播
    prediction = model(data)
    # 计算损失
    loss = (prediction - labels).sum()
    # 反向传播
    loss.backward()
    # 参数更新
    optim.step()
    """
    清除梯度的主要作用是确保每次迭代时
    模型的梯度计算都是独立的
    只反映当前批次的数据误差
    这对于模型能够正确优化和收敛至关重要。
    """
    # 清除梯度 
    optim.zero_grad()
    print(f"Epoch {epoch+1}/{epoch}, Loss:{loss.item():.4f}")

# Differentiation in Autograd

In [2]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
a, b

(tensor([2., 3.], requires_grad=True), tensor([6., 4.], requires_grad=True))

In [3]:
Q = 3*a**3 - b**2

In [4]:
external_grad =  torch.tensor([1., 1.])
Q.backward(gradient = external_grad)

In [5]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])
